sonar.projectKey=dhawal-jaiswal_MyCICD-Repo
sonar.projectName=MyCICD-Repo
sonar.sources=.
sonar.language=py
sonar.organization=dhawal-jaiswal
sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8